name: Calculate Sum

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        required: true
        default: '0'
      number2:
        description: 'Second number'
        required: true
        default: '0'

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate Sum
        id: calculate_sum
        run: |
          number1=${{ github.event.inputs.number1 }}
          number2=${{ github.event.inputs.number2 }}
          sum=$((number1 + number2))
          echo "Sum of $number1 and $number2 is $sum"
          echo "::set-output name=sum::$sum"

      - name: Print Sum
        run: echo "The sum is ${{ steps.calculate_sum.outputs.sum }}"
