name: Select and Print Option

on:
  workflow_dispatch:
    inputs:
      selection:
        description: 'Select an option'
        required: true
        default: 'frontend'
        type: choice
        options:
          - 'frontend'
          - 'backend'

jobs:
  print_option:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]  # Specify Node.js version 16.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Selected Option
        run: |
          selection=${{ github.event.inputs.selection }}
          if [[ "$selection" == "frontend" ]]; then
            echo "Selected option is frontend"
          elif [[ "$selection" == "backend" ]]; then
            echo "Selected option is backend"
          else
            echo "Invalid option selected"
            exit 1
          fi
